### ISSUE TITLE
move to phpstan?

### ISSUE THREAD

**Issue by dereuromark** [spryker-sdk/phpstan-spryker#1]
Discuss moving to

https://github.com/phpstan/phpstan-spryker

as other frameworks also provide their extension packs here
@ondrejmirtes What do you think? Are there any requirements here?

**Comment by dereuromark** [comment]
Then we can implement here our console command wrapper directly as high level convenience access.

**Comment by ondrejmirtes** [comment]
Hi,
in order for an extension to become official one, I have a few requirements:

* Follow same project structure, e. g. similar build.xml with lint/cs/tests/phpstan
* Running on Travis CI
* Follow same structure for README

I see that you're missing the build and also `extension.neon` to include the extension into the analysis.

I also have a section in PHPStan's readme with unofficial extensions so if you don't want to keep these requirements, I can add it there :)

**Comment by ondrejmirtes** [comment]
Hi, I created the repo and invited you. Please make adjustments to the structure and build script.

**Comment by dereuromark** [comment]
Will be done in https://github.com/spryker-sdk/phpstan-spryker/pull/4 
Further discussion there then.
