### ISSUE TITLE
Autocomplete understanding as extension?

### ISSUE THREAD

**Issue by dereuromark** [spryker-sdk/phpstan-spryker#19]
couldn't we write a better phpstan extension to get rid off all the phpstan issues like?
```
Run PHPStan in module Spryker.AvailabilityDataFeed
 ------ -------------------------------------------------------------------------------------------------
  Line   Spryker/Zed/AvailabilityDataFeed/AvailabilityDataFeedDependencyProvider.php
 ------ -------------------------------------------------------------------------------------------------
  52     Call to an undefined method
         Generated\Zed\Ide\AutoCompletion|Spryker\Shared\Kernel\LocatorLocatorInterface::availability().
 ------ -------------------------------------------------------------------------------------------------
```
and alike? So much noise there.
Currently we have 133+ of those lines, and we will need hundreds more, once the other modules also go PHPStan Level 6-8.

The code is
```php
$availabilityQueryContainer = $container->getLocator()
                ->availability()
                ->queryContainer();
```
which calls
```php
    /**
     * @return \Generated\Zed\Ide\AutoCompletion|\Spryker\Shared\Kernel\LocatorLocatorInterface
     */
    public function getLocator()
    {
        return Locator::getInstance();
    }
```

Based on https://github.com/CakeDC/cakephp-phpstan/tree/master/src there should be a way to make it work, right?

**Comment by dereuromark** [comment]
```php
...
 * @method \Generated\Zed\Ide\Availability availability()
...
interface AutoCompletion
{}
```
gets added to a Autocomplete.php file 

we might have to get rid of this old way, or ignore this Autocomplete file (which is for IDE understanding only), and instead provide a phpstan extension that resolves this internally, so it always returns the correct concrete object.

**Comment by ondrejmirtes** [comment]
Yeah, but `\Generated\Zed\Ide\AutoCompletion|\Spryker\Shared\Kernel\LocatorLocatorInterface` is a union of those two types, and LocatorLocatorInterface obviously doesn't have that method. Perhaps you meant an intersection type instead?
